services:
  backend:
    build: .
    container_name: ExpenseTrackerAPI
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
  postgres:
    image: postgres:latest
    container_name: postgres-ExpenseTrackerAPI
    environment:
      POSTGRES_DB: ${DB_POSTGRES}
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data: